name: Run Unit Tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    uses: SilverPineSoftware/UUGithubActions/.github/workflows/uu_android_tests.yml@main
    with:
      module_name: 'library'
    secrets:
      READ_PACKAGES_PAT: ${{ secrets.CI_READ_PACKAGES_GITHUB_TOKEN }}
